### ISSUE TITLE
SolverGadget incorrectly says no error occured when really there was an error

### ISSUE THREAD

**Issue by stefanheule** [StanfordPL/stoke#842]
No, `bool has_error() const` is not the same method as `bool has_error()`.

**Comment by stefanheule** [comment]
@bchurchill: When debugging this, I saw lots of is_sat calls (mostly in bounded.cc, I think) that are not followed by a check for has_error.  That seems like a bug to me, or am I missing something?

**Comment by bchurchill** [comment]
Good find!  This is almost certainly the root cause of #811 too.  I'll mark that as closed since I don't have any evidence to the contrary.  I agree, not having a check for has_error() is a bug.  I doubt that would affect soundness, and in my experiments I rarely see the solver having an error, but yes, it should be fixed as time permits.

**Comment by stefanheule** [comment]
Yeah, it doesn't happen often, but if it does, it is definitely possible to affect soundness.  That's certainly what happened to me (and made me miss the PLDI AEC).  Let's open a wishlist ticket for this: #843.
