### ISSUE TITLE
Tarballs on github pages?

### ISSUE THREAD

**Issue by bchurchill** [StanfordPL/stoke#851]
The github page (stoke.stanford.edu) has a link to download a tarball or zip archive.  In practice, I don't think these work so well because of the submodules required for building.  At least, people don't like dealing with that.  Maybe we should take out these links?  I don't know how to do this off the top of my head.

**Comment by stefanheule** [comment]
Yeah, that's probably a good idea.  I don't know of a way to change how github generates the website from the README automatically without these links, so this might mean we have to set up our own website.

**Comment by stefanheule** [comment]
Another problem is that the website is constantly out of date, because we forget to regenerate it whenever we update the README.  Maybe we should just make a simple website that has 1 paragraph on what STOKE is, maybe links to our papers and then a link to github.  This would solve this issue (tarballs), and should prevent the website from getting out of date because we wouldn't have to update it very often (unlike the README).

What do you think?
