### ISSUE TITLE
Default OPT in Makefile to debug build

### ISSUE THREAD

**Issue by stefanheule** [StanfordPL/stoke#889]
I'd like to change the default for OPT in the makefile to default to a debug build.  This only applies when you are rebuilding a single binary, and that's usually the case when you are developing/debugging, so a debug configuration is much more useful.

**Comment by bchurchill** [comment]
If I understand correctly, if we write "OPT=......" into the .stoke_config file generated by ./configure, each user can set their default choice for OPT themselves.  We could even add a ./configure option, like --debug-singleton-builds that would automatically add this line.  I would prefer having this be an opt-in choice because the debug binaries can be so much slower.

**Comment by stefanheule** [comment]
Nothing would change for the default "make" targets, this would just be about calling a non-top-level target, which at least for me, only happens when I'm debugging, which is why I'm arguing for the better default.

**Comment by bchurchill** [comment]
I understand what you're saying.  Usually when I compile a single top-level binary I don't want debug behavior.

**Comment by bchurchill** [comment]
This is very analogous to how I handle debugging DDEC.  I almost always want the full debug output.  So, whenever I run ./configure I run it with --debug-ddec and sometimes --debug-ceg.  Then I completely forget about the configure script, and the makefile takes care of everything else as I go about debug cycles.  It also makes it easy to have per-machine configurations persist, like those that set the architecture.

**Comment by stefanheule** [comment]
Okay, we can keep the old default if you prefer.  I'm going to implement the ./configure --debug then, that will do a debug build if no other optimization options are given.  Do you want --debug-ceg/ddec to imply --debug, or should they be separate (either is fine with me)?

**Comment by bchurchill** [comment]
I don't think we should be calling this --debug, because that name would
imply to me that _everything_ is always built in debug mode, but we're
talking about something much less than that.  I definitely don't want
--debug-ceg or --debug-ddec to imply the --debug-singleton-builds (as
I'll call it), and I'm guessing you wouldn't want
--debug-singleton-builds to imply --debug-ceg or --debug-ddec.  I could
imagine additionally creating a separate --debug which would imply all
the --debug-\* options.

**Comment by stefanheule** [comment]
Okay, I can call it `--debug-singleton-builds`.

**Comment by stefanheule** [comment]
By the way, I chose a slightly different name (but not --debug).  If you checkout develop, you'll have to run configure again, otherwise the makefile won't work (but it'll error with an appropriate message).
