### ISSUE TITLE
stoke extract errors

### ISSUE THREAD

**Issue by stefanheule** [StanfordPL/stoke#896]
I'm trying to run stoke extract on the attached binary ([a.txt](https://github.com/StanfordPL/stoke/files/264190/a.txt), rename to a.out), but it errors:

```
stoke extract -i ./a.out -o bins
FATAL ERROR: Error: Could not encode movw.s %sp,%bp within 3 bytes.
```

**Comment by stefanheule** [comment]
Changing this to high priority, because it's causing the build to fail.  The integration test sandbox/rip test is failing with

```
stoke extract -i ./test_nibble -o bins > /dev/null
FATAL ERROR: Error: Could not encode movq   %fs:0x28,%rax within 9 bytes.
```

**Comment by bchurchill** [comment]
This fails because we don't support memory segments in x64asm, and I don't think we should either.  Before we just ignored the errors.  Perhaps, now that the disassembler can report errors properly, we can just have stoke extract print a list of functions that couldn't be extracted properly and skip over those?

**Comment by stefanheule** [comment]
Okay, that's totally fine with me (and I can implement that), but just ignoring them definitely didn't seem like the right solution, because those instructions could have been in a valid function.
