### ISSUE TITLE
Stoke testcase for .o files

### ISSUE THREAD

**Issue by Ch0ronomato** [StanfordPL/stoke#930]
Hi all,

Is there a suggestion for how to stoke testcase working with .o files? By "working" I mean either `stoke testcase` itself, or if there is a set of steps that someone can provide on how to reproduce the outcome of `stoke testcase`. I was able to get the other stoke commands to work for a .o file (asked in #925 ) but I'm having difficulties with testcase.

Any guidance would be appreciated.

Ian

**Comment by bchurchill** [comment]
stoke testcase works by running an executable and recording the inputs to a specified function call, along with all memory dereferences.  Then it outputs those values in a format that the stoke tools can parse so they can be fed into the search loop (or however else you want to use them).

.o files include collections of functions, but they aren't executable because they aren't linked and don't have a specified main function.  If you want to get the inputs to a function `foo` in a .o file, you'll need to write a harness in a main function that exercises `foo` on different inputs, for example:

```
extern int foo(int);
int main(int argc, char** argv) {
    for(int i = 0; i < 10; ++i)
        foo(i);
}
```

Then you would do something like `gcc main.c obj.o -o main`.  `main` would be the generated executable file and you could run `stoke testcase` on that.  I haven't tested the above harness, but this is the general idea.  It's best to exercise the function on enough inputs to exercise all the interesting control flow paths and corner cases.

Alternatively, if you're interested in having the SMT solver generating inputs for you, you can try `stoke_tcgen`.  This tool is not polished nor documented, but it exists.  You can expect it to only work on short functions whose instructions are supported by the validator (which includes most general purpose instructions, some SSE instructions, but is more limited once you get to avx/avx2).  But, if your example satisfies this criteria, you can try `stoke_tcgen --target </path/to/extract.s> --output mytcs.tc` and it might just work without further effort.  If it doesn't work, feel free to open a ticket.  ِYou can expect it to produce some debug information on stdout which you can safely ignore.

Let us know if you have any further questions, or feel free to close as your convenience.
