### ISSUE TITLE
stoke testcase does not work for mutable buffers

### ISSUE THREAD

**Issue by stefanheule** [StanfordPL/stoke#947]
It seems that `stoke testcase` is completely broken for binaries that modify memory.  To record the value of memory locations, our PIN tool has the following code

    VOID record_deref(VOID* addr, UINT32 size, bool rip_deref, bool read) {
      // Nothing to do here if we're not recording
      if (!tcs_.size()) {
        return;
      }
      //DEBUG_PINTOOL(cout << "recording deref" << endl;)

      MemoryMap& current = memory_values_.top().back();
      for (size_t i = 0; i < size; ++i) {
        const auto ptr = (uint64_t)addr + i;
        current[ptr] = read ? *((uint8_t*)(ptr)) : 0;
      }
    }

But this just writes 0 for locations that are being written to, which results in 0 in the testcase for any buffer that's being written two.

I think we need to replace

    current[ptr] = read ? *((uint8_t*)(ptr)) : 0;

with

    if (current.find(ptr) == current.end()) current[ptr] = *((uint8_t*)(ptr));

I'm a bit surprised that this hasn't caused any issues so far.  @bchurchill, do you know if this is a known problem?  And if not, are we just never doing things with functions that modify memory in place?

**Comment by bchurchill** [comment]
I doubt it's completely broken -- I've used it on many simple examples that
write memory and seen it work properly.  If a program reads a byte X from
memory, then we want to record byte X into the test case.  But, if the
program writes a byte X, we don't want to include X in the test case since
that's not actually input to the program.  We record a 0 just so that the
test case contains the address so the program doesn't segfault later.  And,
in the past, it has been important to use a value like '0' instead of the
actual value to prevent STOKE from overfitting to the test cases by
cheating and reading the output of a computation from memory as part of its
"optimization".

However, looking at the code, I'm guessing there's a bug when a memory
location is accessed multiple times.  It could be that a location which is
read and later written to is being zeroed out when it shouldn't be?  If
that's the problem, then I think we should have the check you're proposing
along with the old line of code:

if (current.find(ptr) == current.end()) {
  current[ptr] = read ? *((uint8_t*)(ptr)) : 0;
}

Does that match your observations?

**Comment by stefanheule** [comment]
Ah, yeah, we shouldn't store the previous value for addresses that are written to first, so yeah, your solution is better.  It was completely broken for programs that change memory in-place, though, exactly because they wipe out the recorded values.

Thanks for the quick feedback, I'll fix this.
