### ISSUE TITLE
stoke_testcase/pin no longer works on mrwhite (?!)

### ISSUE THREAD

**Issue by stefanheule** [StanfordPL/stoke#971]
It appears that somehow stoke_testcase and pin no longer works on mrwhite.  This is the cause for the test case failures, e.g. from the most recent jenkins run:

    [ RUN      ] IntegrationTest.ExamplesExp
    FATAL ERROR: Unspecified pintool error 65280!

I can't reproduce this on the pinkmans, so it seems only mrwhite is affected.  Did our system, or some libraries on it get updated that could cause this?  I'm a bit lost, so any help would be appreciated.

**Comment by stefanheule** [comment]
@bchurchill: This is the problem I asked you about today, until I realized that actually stoke_testcase no longer works on anything, not just what I'm trying to do.

**Comment by ReverseControl** [comment]
I was able to trace the following:

tools/apps/stoke_testcase.cc: the main function has 4 branches. The third branch depends on "target_arg.has_been_provided()" to call the auto_gen() function to generate the testcases: this branch is never taken. I replaced the condition "target_arg.has_been_provided()"  with "1" and the error I get is:
FATAL ERROR: Auxiliary function (frame_dummy) contains an unsupported instruction: callq %rax. So, at least it is making an attempt to generate the testcases.

Moreover, the header file "src/ext/cpputil/include/command_line/file_arg.h" defines the "FIleArg" class --- target_arg is of this type--- and the class has no method named "has_been_provided()".


On a separate note: what do I do about the "FATAL ERROR" above.

**Comment by jp1729** [comment]
Hello, I am a bit new to github, so I'm not sure this post is the best place to post, but here goes. If you'd like a better method of posting (email, etc) please let me know.

I am trying to test out stoke and to superoptimize some assembly language, so obviously to learn how to get it working, I read the README and did a tutorial using examples/tutorial. However, at the step "testcase" I'm getting an error. I tried redownloading and rebuilding, but it seems to have the same error. I think the error is related to this issue, so I'm posting here:

```
jay@jay-N85-N87-HJ-HJ1-HK1:~/Research/stoke/examples/tutorial$ stoke testcase --config testcase.conf
A:Source/pin/injector_nonmac/auxvector.cpp:CopyAux:CopyAux:291: unexpected AUX VEC type 26

################################################################################
## STACK TRACE
################################################################################
addr2line -C -f -e "/home/jay/Research/stoke/src/ext/pin-2.13-62732-gcc.4.4.7-linux/intel64/bin/pinbin" 0x5558b85b17e9 0x5558b85b2371 0x5558b88196d5 0x5558b881fb04 0x5558b8821d4e 0x5558b880f771 0x5558b881524d 0x5558b88055ec 0x5558b880edb0 0x2b207a31f3f1 0x5558b85a3d5a
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
Detach Service Count: 1
Pin 2.13
Copyright (c) 2003-2013, Intel Corporation. All rights reserved.
@CHARM-VERSION: $Rev: 62728 $
@CHARM-BUILDER: BUILDER
@CHARM-COMPILER: gcc 4.4.7
@CHARM-TARGET: ia32e
@CHARM-CFLAGS:  __OPTIMIZE__=1  __NO_INLINE__=__NO_INLINE__
Aborted (core dumped)
FATAL ERROR: Unspecified pintool error 34304!
```

I'm on Ubuntu 16.04, gcc 4.9, g++ 4.9, libboost 1.58, and pretty sure the cpu is haswell. If you'd like any other information for debugging, please let me know.

Thank you,
Jay Lim

**Comment by stefanheule** [comment]
This is an appropriate place to report this, thanks Jay.

It looks like you might be running into the same (or a similar) issue like I described, even if the output looks a little different for you.  At the moment it seems that stoke_testcase doesn't work on some systems and we don't quite know why.  Ideally we will update PIN and see if that fixes the problem, but for the moment we haven't gotten around to doing that.  We will update this issue as soon as we have made progress on it.

**Comment by bchurchill** [comment]
Out of curiosity, is that why we're seeing these failures?

[  FAILED  ] IntegrationTest.ExamplesTutorial
[  FAILED  ] IntegrationTest.ExamplesExp
[  FAILED  ] IntegrationTest.SandboxFib
[  FAILED  ] IntegrationTest.SandboxRip

**Comment by bchurchill** [comment]
I feel like our integration tests are so crummy we can't tell the difference from a false positive and a true positive.  If only we had time to worry about things like this...

**Comment by stefanheule** [comment]
Yes, but there may be other reasons the tests are failing, too.  That's why it would be good fix this issue soon.

**Comment by sabastiaan** [comment]
Has anybody managed to get stoke testcase working again? After following the README with gcc-4.9 and g++-4.9 I had the same output as jp1729.

Thanks in advance.

EDIT, it seems that it is an issue with pin. Since the currently used pin version only seems to work with older linux kernels. I will take a look later and see if I can upgrade it.

**Comment by bchurchill** [comment]
I haven't looked at this in a while.  Can you tell us what you're trying to
accomplish?  Depending on your problem we might have some working tools for
you to try.

On Mon, Jul 30, 2018 at 5:26 AM, Sebastiaan Peters <notifications@github.com

**Comment by sabastiaan** [comment]
I was trying to create testcase files for an extracted function, this so that I would be able to test the optimizer for a custom cost function I've made.

Also here is what I found thus far: Switching to newer version of pin will be hard, since after 2.4 they made changes such that you can't use any CRT functionality in your own code. Meaning at the very least mutex related code needs to be rewriten using what newer functions of Pin provide, and possible more.

This is assuming that older versions of pin won't work with newer kernel versions, which is merely my speculation based from the only post I could find about this: https://software.intel.com/en-us/forums/intel-vtune-amplifier-xe/topic/735694

There was one stackoverflow post suggesting that passing --ifeellucky flag to PIN would provide a work around, which I haven't tested yet, but probably will try later this week.

**Comment by bchurchill** [comment]
While stoke testcase isn't working so well, we have a few other tools that
might help.  For example, we can use our symbolic execution engine to build
some initial test cases, especially over short execution paths; from these,
you can often modify them manually to get longer test cases.  We also have
a tool that generates random test cases and then modifies them to patch up
memory locations.  Do either of these sound useful for your case?  Can you
describe the function(s) you're trying to optimize?  For instance, how many
lines of assembly code, loops, memory dereferences?  All these things can
impact superoptimization significantly.

I *think* that any mutexes in stoke testcase can safely be removed for your
purposes.  By default there's only one thread in one process, so that
shouldn't be an issue.  However I haven't looked at it in a while so I
could be wrong.

Berkeley

**Comment by sabastiaan** [comment]
I'm using Stoke just to generate a few special case programs because they would be to hard to write by hand in a short time frame. The functions are relatively small, that only do some simple arithmetic. And the end result is only used to proof the existence of some research idea.  From your description both methods seem fine to me.

For now I'm able to limit the functions to ~10 instructions, with no loops and no memory dereferences, although I would like to scale this later to some ~20-30-ish long instructions that have also no loops, and memory dereferences, although I'm not optimizing for speed and only partially for binary size, so there might be a few solutions where both would be preferred.

Sebastiaan

**Comment by sabastiaan** [comment]
@bchurchill Would it be possible to expand the documentation and provide a few examples of the tools you mentioned? It would go a long way for somebody that is new to the project :)

**Comment by bchurchill** [comment]
You're right.  I think in addition to that we might need to do a little
maintenance on the tools.  Honestly, a lot of this depends on me getting
the time once I've made more progress on my thesis.

That said, your situation seems like a good case for randomly-generated
test cases (as long as you don't have any divisions, essentially.  if you
do, the SMT solver might be better).  Try just doing this:

stoke testcase --target /path/to/file.s --max_testcases 30

This has no dependence on PIN features.  It should work with memory
dereferences in most cases, but loops can be hard for it.  Give it a try
and let us know if you have any problems.  Sorry this hasn't been an easy
process for you.

**Comment by bchurchill** [comment]
Okay, I bit the bullet and added some documentation on this in the README!
Hope this helps, and please update us with your experience.

**Comment by sabastiaan** [comment]
First of all, thank you for your help! 

I got the program to generate testcases and synthesize the test example :) 

The command for generating testcases with the SMT solver has a bug, it outputs "Working on path 1" on the first line of the file. The rest of the file seems fine.
In the new documentation, the new shell command examples also miss the extension after `bins/_Z6popcntm`

Maybe it would be advisable to add the tip to compile with optimizations on? Considering that it should strip away things like push/pop %rbp. This was a source of quite a lot of confusion.

I'll keep you guys updated. Also everything seems to be running fine on Ubuntu 18.04 outside of the parts that depend on PIN.

**Comment by bchurchill** [comment]
Thanks for your feedback.  Just did a round of updates on the documentation, and changed the tutorial so it no longer uses pin by default.

**Comment by shrin18** [comment]
FATAL ERROR: Unspecified pintool error 65280!
(while running "stoke@133163eb652d:~/stoke/examples/tutorial$ stoke testcase --config testcase.conf
")
Hello, 

I have got this error and cannot proceed. If someone got similar error please help.

Thanks.
