### ISSUE TITLE
Assembler/disassembler inconsistencies

### ISSUE THREAD

**Issue by stefanheule** [StanfordPL/stoke#974]
Our assembler produces instructions that our disassembler can't parse, and we sometimes parse instructions seemingly incorrectly.

**Comment by stefanheule** [comment]
There are a lot of errors, some in STOKE, some in x64asm.  I'll be fixing them and using this issue for STOKE and https://github.com/StanfordPL/x64asm/issues/240 for x64asm to do it.

**Comment by bchurchill** [comment]
It sounds like we should write a fuzzer for this.  I think we have one
actually but it must not have enough functionality.

On Aug 24, 2017 11:23, "Stefan Heule" <notifications@github.com> wrote:

There are a lot of errors, some in STOKE, some in x64asm. I'll be fixing
them and using this issue for STOKE and StanfordPL/x64asm#240
<https://github.com/StanfordPL/x64asm/issues/240> for x64asm to do it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StanfordPL/stoke/issues/974#issuecomment-324716847>,
or mute
the thread

**Comment by stefanheule** [comment]
Yep, I fixed the fuzzer to more in this issue.  That's party how I found all these issues.

**Comment by stefanheule** [comment]
The new extended fuzzer is still not perfect but it is detecting many more problems then before.  There is also still the issue that we cannot take all instructions and assemble them, then disassemble them and get back the identical (in-memory) represenation.  Partly this is because AT&T syntax is lossy, and partly because there are some in-memory representations that assemble to the same bits, so it's impossible to do (e.g. nop and some versions of `xor eax eax` assemble both to 0x90).
